# yaml-language-server: $schema=https://github.com/connix-io/conclaude/releases/latest/download/conclaude-schema.json
# Conclaude Configuration Template
#
# This is a minimal example configuration file.
# For full documentation of all options, run: conclaude config --docs
# Or see the generated documentation from `cargo doc --open`

# Stop hook - runs when Claude is about to stop
# Stop hook configuration - runs when Claude is about to stop
stop:
  # Structured command format with optional custom error messages
  # Each command can have its own error message, and control output display
  commands:
    - run: "nix fmt"
      showStdout: false
      showStderr: false
      message: "Nix formatting failed - please fix formatting errors before continuing"
      maxOutputLines: 5
    - run: "go install ."
      showStdout: false
      showStderr: false
      message: "Installing go dependencies failed - please fix installation errors before continuing"
      maxOutputLines: 5
    - run: "nix develop -c 'tests'"
      showStdout: false
      showStderr: false
      message: "Tests (nix develop -c 'tests') failed - please fix failing tests before continuing"
      maxOutputLines: 5
    - run: "nix develop -c 'lint'"
      showStdout: false
      showStderr: false
      message: "Linting (nix develop -c 'lint') failed - please fix linting errors before continuing"
      maxOutputLines: 5
    - run: "spectr validate --all --strict"
      showStdout: false
      showStderr: false
      message: "Spectr validation failed - please fix validation errors before continuing"
      maxOutputLines: 5
  # Examples:
  # commands:
  #   - run: "echo 'Starting build...'"
  #     showStdout: true    # User/Claude sees: "Starting build..."
  #
  #   - run: "npm test"
  #     showStdout: true    # Show test results to user/Claude
  #     showStderr: true    # Show test errors to user/Claude
  #     message: "Tests failed - please fix failing tests before continuing"
  #     maxOutputLines: 100 # Limit output to last 100 lines (1-10000)
  #
  #   - run: "npm run build"
  #     showStderr: true    # Only show build errors to user/Claude, hide stdout
  #     message: "Build failed - please fix compilation errors"
  #     maxOutputLines: 50  # Limit build output to last 50 lines

  # Example:
  # - run: "npm test"
  #   showStdout: true
  #   showStderr: true
  #   message: "Tests failed"
  #   maxOutputLines: 100
  #   timeout: 300

  infinite: false
  infiniteMessage: "continue working on the task"

# Subagent stop hook - runs when subagents finish
subagentStop:
  commands:
    coder:
      - run: "nix develop -c 'lint'"
        showStdout: true
        showStderr: true
        message: "Linting (nix develop -c 'lint') failed"
        maxOutputLines: 100
  # Example:
  # coder:
  #   - run: "npm run lint"
  #     showStdout: true
  #     message: "Linting failed"
  # test*:
  #   - run: "npm test"
  #     showStderr: true

# Pre-tool-use hook - file protection and tool validation
preToolUse:
  # Prevent files at repository root
  preventRootAdditions: true

  # Protected files (glob patterns)
  uneditableFiles:
    - ".conclaude.yml"
    - ".conclaude.yaml"
  # Examples:
  # - "*.lock"
  # - pattern: ".env*"
  #   message: "Environment files contain secrets"

  # Prevent editing git-ignored files
  preventUpdateGitIgnored: false

  # Tool usage rules
  toolUsageValidation: []
  # Example:
  # - tool: "Write"
  #   pattern: "**/*.js"
  #   action: "allow"
  # - tool: "Bash"
  #   commandPattern: "git push --force*"
  #   action: "block"
  #   message: "Force push not allowed"

  # Directories where additions are prevented
  preventAdditions: []
  # Example: ["dist", "build"]

  # Prevent editing generated files
  preventGeneratedFileEdits: true
  generatedFileMessage: null

# System notifications
notifications:
  enabled: false
  hooks: [] # ["*"] for all, or ["Stop", "PreToolUse"]
  showErrors: false
  showSuccess: false
  showSystemEvents: true
# Permission request hook - auto-approve/deny tools
# Uncomment to enable:
#
# permissionRequest:
#   default: deny  # "allow" or "deny"
#   allow:
#     - "Read"
#     - "Glob"
#     - "Grep"
#     - "Edit"
#     - "Write"
#   deny:
#     - "BashOutput"
#     - "KillShell"
