// Package cmd provides command-line interface implementations.
// This file contains the JSONC writer for the accept command.
package cmd

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/connerohnesorge/spectr/internal/parsers"
)

// tasksJSONHeader is the comprehensive JSONC comment header prepended to
// tasks.jsonc files. It explains status values, transitions, and workflow.
const tasksJSONHeader = `// Spectr Tasks File (JSONC)
//
// This file contains machine-readable task definitions for a Spectr change.
// JSONC format allows comments while maintaining JSON compatibility.
//
// Status Values:
//   - "pending"     : Task has not been started yet
//   - "in_progress" : Task is currently being worked on
//   - "completed"   : Task has been finished and verified
//
// Status Transitions:
//   pending -> in_progress -> completed
//
//   Tasks should only move forward through these states.
//   Do not skip states or move backward.
//
// Workflow:
//   1. Before starting work on a task, mark it as "in_progress"
//   2. Complete the implementation for the task
//   3. Verify the work is correct and complete
//   4. Mark the task as "completed" only after verification
//   5. Work through tasks sequentially within each section
//   6. Complete all tasks in a section before moving to the next
//
// Note: This file is auto-generated by 'spectr accept'. Manual edits to
// task status are expected, but structure changes may be overwritten.
//

`

// writeTasksJSONC writes tasks to a tasks.jsonc file with header.
// Prepends tasksJSONHeader to the JSON data (see parsers/types.go).
func writeTasksJSONC(
	path string,
	tasks []parsers.Task,
) error {
	tasksFile := parsers.TasksFile{
		Version: 1,
		Tasks:   tasks,
	}

	jsonData, err := json.MarshalIndent(
		tasksFile,
		"",
		"  ",
	)
	if err != nil {
		return fmt.Errorf(
			"failed to marshal tasks to JSON: %w",
			err,
		)
	}

	// Prepend the JSONC header to the JSON data
	output := tasksJSONHeader + string(jsonData)

	if err := os.WriteFile(path, []byte(output), filePerm); err != nil {
		return fmt.Errorf(
			"failed to write tasks.jsonc: %w",
			err,
		)
	}

	return nil
}
