// Package cmd provides command-line interface implementations.
// This file contains the JSONC writer for the accept command.
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/connerohnesorge/spectr/internal/config"
	"github.com/connerohnesorge/spectr/internal/parsers"
)

// tasksJSONHeader is the comprehensive JSONC comment header prepended to
// tasks.jsonc files. It explains status values, transitions, and workflow.
const tasksJSONHeader = `// Spectr Tasks File (JSONC)
//
// This file contains machine-readable task definitions for a Spectr change.
// JSONC format allows comments while maintaining JSON compatibility.
//
// Status Values:
//   - "pending"     : Task has not been started yet
//   - "in_progress" : Task is currently being worked on
//   - "completed"   : Task has been finished and verified
//
// Status Transitions:
//   pending -> in_progress -> completed
//
//   Tasks should only move forward through these states.
//   Do not skip states or move backward.
//
// Workflow:
//   1. BEFORE starting work on a task, mark it as "in_progress"
//   2. Complete the implementation for the task
//   3. Verify the work is correct and complete
//   4. IMMEDIATELY mark the task as "completed" after verification
//   5. Move to the next task and repeat
//
// IMPORTANT - Update Status Immediately:
//   - Update each task's status IMMEDIATELY after it transitions
//   - Do NOT batch status updates at the end of all work
//   - Do NOT wait until all tasks are done to update statuses
//   - This file should reflect accurate progress at any point in time
//   - Using a single edit to mark a task completed AND the next task
//     in_progress is allowed (this is a single transition, not batching)
//
// Note: This file is auto-generated by 'spectr accept'. Manual edits to
// task status are expected, but structure changes may be overwritten.
// The original tasks.md file is preserved alongside tasks.jsonc to retain
// human-readable formatting, links, and context.
//

`

// writeTasksJSONC writes tasks to a tasks.jsonc file with header.
// Prepends tasksJSONHeader to the JSON data (see parsers/types.go).
// If appendCfg is provided, appends configured tasks with sequential IDs.
func writeTasksJSONC(
	path string,
	tasks []parsers.Task,
	appendCfg *config.AppendTasksConfig,
) error {
	// Append configured tasks if present
	allTasks := tasks
	if appendCfg != nil && appendCfg.HasTasks() {
		appendedTasks := createAppendedTasks(tasks, appendCfg)
		allTasks = append(allTasks, appendedTasks...)
	}

	tasksFile := parsers.TasksFile{
		Version: 1,
		Tasks:   allTasks,
	}

	jsonData, err := json.MarshalIndent(
		tasksFile,
		"",
		"  ",
	)
	if err != nil {
		return fmt.Errorf(
			"failed to marshal tasks to JSON: %w",
			err,
		)
	}

	// Prepend the JSONC header to the JSON data
	output := tasksJSONHeader + string(jsonData)

	if err := os.WriteFile(path, []byte(output), filePerm); err != nil {
		return fmt.Errorf(
			"failed to write tasks.jsonc: %w",
			err,
		)
	}

	return nil
}

// createAppendedTasks creates Task structs from the append config.
// It generates sequential task IDs continuing from the last existing task.
// For example, if the last task ID was 3.2, appended tasks start at 4.1.
func createAppendedTasks(
	existingTasks []parsers.Task,
	cfg *config.AppendTasksConfig,
) []parsers.Task {
	nextSectionNum := findNextSectionNumber(existingTasks)
	section := cfg.GetSection()

	tasks := make([]parsers.Task, 0, len(cfg.Tasks))
	for i, desc := range cfg.Tasks {
		taskID := fmt.Sprintf("%d.%d", nextSectionNum, i+1)
		tasks = append(tasks, parsers.Task{
			ID:          taskID,
			Section:     section,
			Description: desc,
			Status:      parsers.TaskStatusPending,
		})
	}

	return tasks
}

// findNextSectionNumber determines the next section number for appended tasks.
// It parses existing task IDs to find the highest section number, then adds 1.
// Returns 1 if no existing tasks or task IDs are not in expected format.
func findNextSectionNumber(tasks []parsers.Task) int {
	maxSection := 0
	for _, task := range tasks {
		// Parse section number from task ID (e.g., "3.2" -> 3)
		parts := strings.Split(task.ID, ".")
		if len(parts) < 1 {
			continue
		}
		sectionNum, err := strconv.Atoi(parts[0])
		if err != nil {
			continue
		}
		if sectionNum > maxSection {
			maxSection = sectionNum
		}
	}

	return maxSection + 1
}
