package pr

import (
	"strings"
	"testing"
)

func TestRenderArchiveCommitMessage(t *testing.T) {
	tests := []struct {
		name     string
		data     ArchiveCommitData
		contains []string
	}{
		{
			name: "basic archive commit",
			data: ArchiveCommitData{
				ChangeID:    "add-user-auth",
				ArchivePath: "spectr/changes/archive/2024-01-15-add-user-auth",
				Added:       5,
				Modified:    3,
				Removed:     1,
				Renamed:     2,
			},
			contains: []string{
				"spectr(archive): add-user-auth",
				"Archived to: spectr/changes/archive/2024-01-15-add-user-auth",
				"+ 5 added",
				"~ 3 modified",
				"- 1 removed",
				"-> 2 renamed",
				"Generated by: spectr pr archive",
			},
		},
		{
			name: "zero counts",
			data: ArchiveCommitData{
				ChangeID:    "empty-change",
				ArchivePath: "spectr/changes/archive/2024-01-15-empty-change",
				Added:       0,
				Modified:    0,
				Removed:     0,
				Renamed:     0,
			},
			contains: []string{
				"spectr(archive): empty-change",
				"+ 0 added",
				"~ 0 modified",
				"- 0 removed",
				"-> 0 renamed",
			},
		},
		{
			name: "only added operations",
			data: ArchiveCommitData{
				ChangeID:    "new-feature",
				ArchivePath: "spectr/changes/archive/2024-02-20-new-feature",
				Added:       10,
				Modified:    0,
				Removed:     0,
				Renamed:     0,
			},
			contains: []string{
				"+ 10 added",
				"~ 0 modified",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderArchiveCommitMessage(tt.data)
			if err != nil {
				t.Fatalf("RenderArchiveCommitMessage() error = %v", err)
			}

			for _, substr := range tt.contains {
				if !strings.Contains(result, substr) {
					t.Errorf(
						"RenderArchiveCommitMessage() missing %q in:\n%s",
						substr, result,
					)
				}
			}
		})
	}
}

func TestRenderNewCommitMessage(t *testing.T) {
	tests := []struct {
		name     string
		data     NewCommitData
		contains []string
	}{
		{
			name: "basic new commit",
			data: NewCommitData{
				ChangeID:     "add-payment-system",
				ProposalPath: "spectr/changes/add-payment-system",
			},
			contains: []string{
				"spectr(proposal): add-payment-system",
				"Proposal for review: spectr/changes/add-payment-system",
				"Generated by: spectr pr new",
			},
		},
		{
			name: "nested change ID",
			data: NewCommitData{
				ChangeID:     "feature/user-dashboard",
				ProposalPath: "spectr/changes/feature/user-dashboard",
			},
			contains: []string{
				"spectr(proposal): feature/user-dashboard",
				"Proposal for review: spectr/changes/feature/user-dashboard",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderNewCommitMessage(tt.data)
			if err != nil {
				t.Fatalf("RenderNewCommitMessage() error = %v", err)
			}

			for _, substr := range tt.contains {
				if !strings.Contains(result, substr) {
					t.Errorf(
						"RenderNewCommitMessage() missing %q in:\n%s",
						substr, result,
					)
				}
			}
		})
	}
}

func TestRenderArchivePRBody(t *testing.T) {
	tests := []struct {
		name     string
		data     ArchivePRBodyData
		contains []string
	}{
		{
			name: "full archive PR body",
			data: ArchivePRBodyData{
				ChangeID:     "add-user-auth",
				ArchivePath:  "spectr/changes/archive/2024-01-15-add-user-auth",
				Added:        5,
				Modified:     3,
				Removed:      1,
				Renamed:      2,
				Capabilities: []string{"authentication", "user-management"},
			},
			contains: []string{
				"## Summary",
				"`add-user-auth`",
				"`spectr/changes/archive/2024-01-15-add-user-auth`",
				"## Spec Updates",
				"| Operation | Count |",
				"| Added     | 5 |",
				"| Modified  | 3 |",
				"| Removed   | 1 |",
				"| Renamed   | 2 |",
				"**Updated capabilities**:",
				"- authentication",
				"- user-management",
				"## Review Checklist",
				"- [ ] Archived change structure is complete",
				"- [ ] Spec deltas are accurate",
				"- [ ] Merged spec content is correct",
				"`spectr pr archive`",
			},
		},
		{
			name: "empty capabilities list",
			data: ArchivePRBodyData{
				ChangeID:     "minor-fix",
				ArchivePath:  "spectr/changes/archive/2024-01-15-minor-fix",
				Added:        0,
				Modified:     1,
				Removed:      0,
				Renamed:      0,
				Capabilities: nil,
			},
			contains: []string{
				"`minor-fix`",
				"| Modified  | 1 |",
				"**Updated capabilities**:",
			},
		},
		{
			name: "single capability",
			data: ArchivePRBodyData{
				ChangeID:     "single-cap",
				ArchivePath:  "spectr/changes/archive/2024-01-15-single-cap",
				Added:        1,
				Modified:     0,
				Removed:      0,
				Renamed:      0,
				Capabilities: []string{"core"},
			},
			contains: []string{
				"- core",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderArchivePRBody(tt.data)
			if err != nil {
				t.Fatalf("RenderArchivePRBody() error = %v", err)
			}

			for _, substr := range tt.contains {
				if !strings.Contains(result, substr) {
					t.Errorf(
						"RenderArchivePRBody() missing %q in:\n%s",
						substr, result,
					)
				}
			}
		})
	}
}

func TestRenderNewPRBody(t *testing.T) {
	tests := []struct {
		name     string
		data     NewPRBodyData
		contains []string
	}{
		{
			name: "full new PR body",
			data: NewPRBodyData{
				ChangeID:     "add-payment-system",
				ProposalPath: "spectr/changes/add-payment-system",
			},
			contains: []string{
				"## Summary",
				"`add-payment-system`",
				"`spectr/changes/add-payment-system`",
				"## Files",
				"`proposal.md` - Change overview",
				"`tasks.md` - Implementation checklist",
				"`specs/` - Delta specifications",
				"## Review Checklist",
				"- [ ] Proposal addresses the stated problem",
				"- [ ] Delta specs are properly formatted",
				"- [ ] Tasks are clear and actionable",
				"`spectr pr new`",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderNewPRBody(tt.data)
			if err != nil {
				t.Fatalf("RenderNewPRBody() error = %v", err)
			}

			for _, substr := range tt.contains {
				if !strings.Contains(result, substr) {
					t.Errorf(
						"RenderNewPRBody() missing %q in:\n%s",
						substr, result,
					)
				}
			}
		})
	}
}

func TestRenderArchivePRBody_MarkdownTableFormat(t *testing.T) {
	data := ArchivePRBodyData{
		ChangeID:     "test-change",
		ArchivePath:  "spectr/changes/archive/2024-01-15-test-change",
		Added:        1,
		Modified:     2,
		Removed:      3,
		Renamed:      4,
		Capabilities: []string{"cap1"},
	}

	result, err := RenderArchivePRBody(data)
	if err != nil {
		t.Fatalf("RenderArchivePRBody() error = %v", err)
	}

	// Verify markdown table structure
	tableLines := []string{
		"| Operation | Count |",
		"|-----------|-------|",
		"| Added     | 1 |",
		"| Modified  | 2 |",
		"| Removed   | 3 |",
		"| Renamed   | 4 |",
	}

	for _, line := range tableLines {
		if !strings.Contains(result, line) {
			t.Errorf("Missing table line %q in:\n%s", line, result)
		}
	}
}
