package pr

import (
	"bytes"
	"text/template"
)

// ArchiveCommitData contains data for rendering archive commit messages.
type ArchiveCommitData struct {
	// ChangeID is the identifier of the archived change.
	ChangeID string
	// ArchivePath is the path where the change was archived.
	ArchivePath string
	// Added is the count of requirements added.
	Added int
	// Modified is the count of requirements modified.
	Modified int
	// Removed is the count of requirements removed.
	Removed int
	// Renamed is the count of requirements renamed.
	Renamed int
}

// NewCommitData contains data for rendering new proposal commit messages.
type NewCommitData struct {
	// ChangeID is the identifier of the proposed change.
	ChangeID string
	// ProposalPath is the path to the proposal directory.
	ProposalPath string
}

// ArchivePRBodyData contains data for rendering archive PR bodies.
type ArchivePRBodyData struct {
	// ChangeID is the identifier of the archived change.
	ChangeID string
	// ArchivePath is the path where the change was archived.
	ArchivePath string
	// Added is the count of requirements added.
	Added int
	// Modified is the count of requirements modified.
	Modified int
	// Removed is the count of requirements removed.
	Removed int
	// Renamed is the count of requirements renamed.
	Renamed int
	// Capabilities lists the capability names that were updated.
	Capabilities []string
}

// NewPRBodyData contains data for rendering new proposal PR bodies.
type NewPRBodyData struct {
	// ChangeID is the identifier of the proposed change.
	ChangeID string
	// ProposalPath is the path to the proposal directory.
	ProposalPath string
}

// Template strings for commit messages and PR bodies.
const (
	archiveCommitTemplate = `spectr(archive): {{.ChangeID}}

Archived to: {{.ArchivePath}}

Spec operations applied:
+ {{.Added}} added
~ {{.Modified}} modified
- {{.Removed}} removed
-> {{.Renamed}} renamed

Generated by: spectr pr archive`

	newCommitTemplate = `spectr(proposal): {{.ChangeID}}

Proposal for review: {{.ProposalPath}}

Generated by: spectr pr new`

	archivePRBodyTemplate = `## Summary

Archived completed change: ` + "`{{.ChangeID}}`" + `

**Location**: ` + "`{{.ArchivePath}}`" + `

## Spec Updates

| Operation | Count |
|-----------|-------|
| Added     | {{.Added}} |
| Modified  | {{.Modified}} |
| Removed   | {{.Removed}} |
| Renamed   | {{.Renamed}} |

**Updated capabilities**:
{{range .Capabilities}}- {{.}}
{{end}}
## Review Checklist

- [ ] Archived change structure is complete
- [ ] Spec deltas are accurate
- [ ] Merged spec content is correct

---
*Generated by ` + "`spectr pr archive`" + `*`

	newPRBodyTemplate = `## Summary

Proposal for review: ` + "`{{.ChangeID}}`" + `

**Location**: ` + "`{{.ProposalPath}}`" + `

## Files

- ` + "`proposal.md`" + ` - Change overview
- ` + "`tasks.md`" + ` - Implementation checklist
- ` + "`specs/`" + ` - Delta specifications

## Review Checklist

- [ ] Proposal addresses the stated problem
- [ ] Delta specs are properly formatted
- [ ] Tasks are clear and actionable

---
*Generated by ` + "`spectr pr new`" + `*`
)

// RenderArchiveCommitMessage renders a commit message for archive operations.
func RenderArchiveCommitMessage(data ArchiveCommitData) (string, error) {
	tmpl, err := template.New("archiveCommit").Parse(archiveCommitTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// RenderNewCommitMessage renders a commit message for new proposal operations.
func RenderNewCommitMessage(data NewCommitData) (string, error) {
	tmpl, err := template.New("newCommit").Parse(newCommitTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// RenderArchivePRBody renders a PR body for archive operations.
func RenderArchivePRBody(data ArchivePRBodyData) (string, error) {
	tmpl, err := template.New("archivePRBody").Parse(archivePRBodyTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// RenderNewPRBody renders a PR body for new proposal operations.
func RenderNewPRBody(data NewPRBodyData) (string, error) {
	tmpl, err := template.New("newPRBody").Parse(newPRBodyTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}
