package pr

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/connerohnesorge/spectr/internal/archive"
)

// Mode constants for PR template rendering
const (
	ModeArchive = "archive"
	ModeNew     = "new"
	ModeDelete  = "delete"
)

// CommitTemplateData holds data for rendering commit messages.
type CommitTemplateData struct {
	ChangeID    string // The change identifier
	ArchivePath string // Full archive path (archive mode only)
	Mode        string // "archive" or "new"

	// Counts tracks spec operation counts (archive mode only)
	Counts archive.OperationCounts
}

// PRTemplateData holds data for rendering PR bodies.
type PRTemplateData struct {
	ChangeID     string   // The change identifier
	ArchivePath  string   // Full archive path (archive mode only)
	Capabilities []string // Updated capability names (archive mode only)
	Mode         string   // "archive" or "new"

	// Counts tracks spec operation counts (archive mode only)
	Counts archive.OperationCounts
}

// Template strings for commit messages
const archiveCommitTemplate = `spectr(archive): {{.ChangeID}}

Archived to: {{.ArchivePath}}

Spec operations applied:
{{- if gt .Counts.Added 0}}
+ {{.Counts.Added}} added
{{- end}}
{{- if gt .Counts.Modified 0}}
~ {{.Counts.Modified}} modified
{{- end}}
{{- if gt .Counts.Removed 0}}
- {{.Counts.Removed}} removed
{{- end}}
{{- if gt .Counts.Renamed 0}}
-> {{.Counts.Renamed}} renamed
{{- end}}

Generated by: spectr pr archive`

const newCommitTemplate = `spectr(proposal): {{.ChangeID}}

Proposal for review: spectr/changes/{{.ChangeID}}/

Generated by: spectr pr new`

const deleteCommitTemplate = `spectr: delete {{.ChangeID}} spec

Deleted spec: spectr/specs/{{.ChangeID}}/

Generated by: spectr pr delete`

// Template strings for PR bodies (markdown)
const archivePRBodyTemplate = `## Summary

Archived completed change: ` + "`{{.ChangeID}}`" + `

**Location**: ` + "`{{.ArchivePath}}`" + `

## Spec Updates

| Operation | Count |
|-----------|-------|
| Added     | {{.Counts.Added}} |
| Modified  | {{.Counts.Modified}} |
| Removed   | {{.Counts.Removed}} |
| Renamed   | {{.Counts.Renamed}} |

{{- if .Capabilities}}

**Updated capabilities**:
{{range .Capabilities}}- {{.}}
{{end}}
{{- end}}

## Review Checklist

- [ ] Archived change structure is complete
- [ ] Spec deltas are accurate
- [ ] Merged spec content is correct

---
*Generated by ` + "`spectr pr archive`" + `*`

const newPRBodyTemplate = `## Summary

Proposal for review: ` + "`{{.ChangeID}}`" + `

**Location**: ` + "`spectr/changes/{{.ChangeID}}/`" + `

## Files

- ` + "`proposal.md`" + ` - Change overview
- ` + "`tasks.md`" + ` - Implementation checklist
- ` + "`specs/`" + ` - Delta specifications

## Review Checklist

- [ ] Proposal addresses the stated problem
- [ ] Delta specs are properly formatted
- [ ] Tasks are clear and actionable

---
*Generated by ` + "`spectr pr new`" + `*`

const deletePRBodyTemplate = `## Summary

Deletes spec: ` + "`{{.ChangeID}}`" + `

**Removed**: ` + "`spectr/specs/{{.ChangeID}}/`" + `

## Review Checklist

- [ ] Spec is no longer needed
- [ ] No active changes reference this spec

---
*Generated by ` + "`spectr pr delete`" + `*`

// Parsed templates (initialized once)
var (
	archiveCommitTmpl *template.Template
	newCommitTmpl     *template.Template
	deleteCommitTmpl  *template.Template
	archivePRBodyTmpl *template.Template
	newPRBodyTmpl     *template.Template
	deletePRBodyTmpl  *template.Template
)

func init() {
	archiveCommitTmpl = template.Must(
		template.New("archiveCommit").Parse(archiveCommitTemplate),
	)
	newCommitTmpl = template.Must(
		template.New("newCommit").Parse(newCommitTemplate),
	)
	deleteCommitTmpl = template.Must(
		template.New("deleteCommit").Parse(deleteCommitTemplate),
	)
	archivePRBodyTmpl = template.Must(
		template.New("archivePRBody").Parse(archivePRBodyTemplate),
	)
	newPRBodyTmpl = template.Must(
		template.New("newPRBody").Parse(newPRBodyTemplate),
	)
	deletePRBodyTmpl = template.Must(
		template.New("deletePRBody").Parse(deletePRBodyTemplate),
	)
}

// RenderCommitMessage renders the appropriate commit message based on the mode.
func RenderCommitMessage(data CommitTemplateData) (string, error) {
	var buf bytes.Buffer
	var err error

	switch data.Mode {
	case ModeArchive:
		err = archiveCommitTmpl.Execute(&buf, data)
	case ModeNew:
		err = newCommitTmpl.Execute(&buf, data)
	case ModeDelete:
		err = deleteCommitTmpl.Execute(&buf, data)
	default:
		return "", fmt.Errorf("unknown mode: %s", data.Mode)
	}

	if err != nil {
		return "", fmt.Errorf("render commit message: %w", err)
	}

	return strings.TrimSpace(buf.String()), nil
}

// RenderPRBody renders the appropriate PR body based on the mode.
func RenderPRBody(data PRTemplateData) (string, error) {
	var buf bytes.Buffer
	var err error

	switch data.Mode {
	case ModeArchive:
		err = archivePRBodyTmpl.Execute(&buf, data)
	case ModeNew:
		err = newPRBodyTmpl.Execute(&buf, data)
	case ModeDelete:
		err = deletePRBodyTmpl.Execute(&buf, data)
	default:
		return "", fmt.Errorf("unknown mode: %s", data.Mode)
	}

	if err != nil {
		return "", fmt.Errorf("render PR body: %w", err)
	}

	return strings.TrimSpace(buf.String()), nil
}

// GetPRTitle returns the PR title for the given change ID and mode.
func GetPRTitle(changeID, mode string) string {
	switch mode {
	case ModeArchive:
		return fmt.Sprintf("spectr(archive): %s", changeID)
	case ModeNew:
		return fmt.Sprintf("spectr(proposal): %s", changeID)
	case ModeDelete:
		return fmt.Sprintf("spectr: Delete %s spec", changeID)
	default:
		return fmt.Sprintf("spectr: %s", changeID)
	}
}
