package pr

import (
	"strings"
	"testing"

	"github.com/connerohnesorge/spectr/internal/archive"
)

// TestRenderCommitMessage_Archive tests archive mode commit message rendering.
func TestRenderCommitMessage_Archive(t *testing.T) {
	tests := []struct {
		name     string
		data     CommitTemplateData
		expected []string // strings that should be present in output
	}{
		{
			name: "all counts present",
			data: CommitTemplateData{
				ChangeID:    "add-feature-x",
				ArchivePath: "spectr/accepted/add-feature-x",
				Mode:        ModeArchive,
				Counts: archive.OperationCounts{
					Added:    3,
					Modified: 2,
					Removed:  1,
					Renamed:  1,
				},
			},
			expected: []string{
				"spectr(archive): add-feature-x",
				"Archived to: spectr/accepted/add-feature-x",
				"Spec operations applied:",
				"+ 3 added",
				"~ 2 modified",
				"- 1 removed",
				"-> 1 renamed",
				"Generated by: spectr pr archive",
			},
		},
		{
			name: "only added counts",
			data: CommitTemplateData{
				ChangeID:    "new-api",
				ArchivePath: "spectr/accepted/new-api",
				Mode:        ModeArchive,
				Counts: archive.OperationCounts{
					Added:    5,
					Modified: 0,
					Removed:  0,
					Renamed:  0,
				},
			},
			expected: []string{
				"spectr(archive): new-api",
				"+ 5 added",
				"Generated by: spectr pr archive",
			},
		},
		{
			name: "only modified counts",
			data: CommitTemplateData{
				ChangeID:    "update-docs",
				ArchivePath: "spectr/accepted/update-docs",
				Mode:        ModeArchive,
				Counts: archive.OperationCounts{
					Added:    0,
					Modified: 4,
					Removed:  0,
					Renamed:  0,
				},
			},
			expected: []string{
				"spectr(archive): update-docs",
				"~ 4 modified",
				"Generated by: spectr pr archive",
			},
		},
		{
			name: "no counts (zero values)",
			data: CommitTemplateData{
				ChangeID:    "empty-change",
				ArchivePath: "spectr/accepted/empty-change",
				Mode:        ModeArchive,
				Counts: archive.OperationCounts{
					Added:    0,
					Modified: 0,
					Removed:  0,
					Renamed:  0,
				},
			},
			expected: []string{
				"spectr(archive): empty-change",
				"Archived to: spectr/accepted/empty-change",
				"Spec operations applied:",
				"Generated by: spectr pr archive",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderCommitMessage(tt.data)
			if err != nil {
				t.Fatalf("RenderCommitMessage() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf(
						"RenderCommitMessage() missing expected string %q\nGot:\n%s",
						exp,
						result,
					)
				}
			}
		})
	}

	// Also test that zero counts do NOT appear
	t.Run("zero counts not displayed", func(t *testing.T) {
		data := CommitTemplateData{
			ChangeID:    "partial",
			ArchivePath: "spectr/accepted/partial",
			Mode:        ModeArchive,
			Counts: archive.OperationCounts{
				Added:    2,
				Modified: 0,
				Removed:  0,
				Renamed:  0,
			},
		}
		result, err := RenderCommitMessage(data)
		if err != nil {
			t.Fatalf("RenderCommitMessage() error = %v", err)
		}

		// Should NOT contain modified, removed, or renamed
		if strings.Contains(result, "modified") {
			t.Error("Expected no 'modified' line when count is 0")
		}
		if strings.Contains(result, "removed") {
			t.Error("Expected no 'removed' line when count is 0")
		}
		if strings.Contains(result, "renamed") {
			t.Error("Expected no 'renamed' line when count is 0")
		}
	})
}

// TestRenderCommitMessage_Delete tests delete mode commit message rendering.
func TestRenderCommitMessage_Delete(t *testing.T) {
	tests := []struct {
		name     string
		data     CommitTemplateData
		expected []string
	}{
		{
			name: "basic delete",
			data: CommitTemplateData{
				ChangeID: "cli-interface",
				Mode:     ModeDelete,
			},
			expected: []string{
				"spectr: delete cli-interface spec",
				"Deleted spec: spectr/specs/cli-interface/",
				"Generated by: spectr pr delete",
			},
		},
		{
			name: "hyphenated spec id",
			data: CommitTemplateData{
				ChangeID: "user-authentication-module",
				Mode:     ModeDelete,
			},
			expected: []string{
				"spectr: delete user-authentication-module spec",
				"spectr/specs/user-authentication-module/",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderCommitMessage(tt.data)
			if err != nil {
				t.Fatalf("RenderCommitMessage() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf(
						"RenderCommitMessage() missing expected string %q\nGot:\n%s",
						exp,
						result,
					)
				}
			}
		})
	}
}

// TestRenderCommitMessage_New tests new mode commit message rendering.
func TestRenderCommitMessage_New(t *testing.T) {
	tests := []struct {
		name     string
		data     CommitTemplateData
		expected []string
	}{
		{
			name: "basic new proposal",
			data: CommitTemplateData{
				ChangeID: "add-new-feature",
				Mode:     ModeNew,
			},
			expected: []string{
				"spectr(proposal): add-new-feature",
				"Proposal for review: spectr/changes/add-new-feature/",
				"Generated by: spectr pr new",
			},
		},
		{
			name: "hyphenated change id",
			data: CommitTemplateData{
				ChangeID: "my-complex-change-id",
				Mode:     ModeNew,
			},
			expected: []string{
				"spectr(proposal): my-complex-change-id",
				"spectr/changes/my-complex-change-id/",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderCommitMessage(tt.data)
			if err != nil {
				t.Fatalf("RenderCommitMessage() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf(
						"RenderCommitMessage() missing expected string %q\nGot:\n%s",
						exp,
						result,
					)
				}
			}
		})
	}
}

// TestRenderCommitMessage_InvalidMode tests that invalid modes return an error.
func TestRenderCommitMessage_InvalidMode(t *testing.T) {
	tests := []struct {
		name string
		mode string
	}{
		{name: "empty mode", mode: ""},
		{name: "unknown mode", mode: "unknown"},
		{name: "typo in archive", mode: "archiv"},
		{name: "case sensitive", mode: "Archive"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data := CommitTemplateData{
				ChangeID: "test-change",
				Mode:     tt.mode,
			}
			result, err := RenderCommitMessage(data)
			if err == nil {
				t.Errorf(
					"RenderCommitMessage() expected error for mode %q, got result: %s",
					tt.mode,
					result,
				)
			}
			if !strings.Contains(err.Error(), "unknown mode") {
				t.Errorf("RenderCommitMessage() error should mention 'unknown mode', got: %v", err)
			}
		})
	}
}

// TestRenderPRBody_Archive tests archive mode PR body rendering.
func TestRenderPRBody_Archive(t *testing.T) {
	tests := []struct {
		name     string
		data     PRTemplateData
		expected []string
		absent   []string // strings that should NOT be present
	}{
		{
			name: "full data with capabilities",
			data: PRTemplateData{
				ChangeID:    "add-auth-system",
				ArchivePath: "spectr/accepted/add-auth-system",
				Mode:        ModeArchive,
				Capabilities: []string{
					"user-authentication",
					"session-management",
					"token-validation",
				},
				Counts: archive.OperationCounts{
					Added:    5,
					Modified: 2,
					Removed:  1,
					Renamed:  0,
				},
			},
			expected: []string{
				"## Summary",
				"`add-auth-system`",
				"**Location**: `spectr/accepted/add-auth-system`",
				"## Spec Updates",
				"| Operation | Count |",
				"| Added     | 5 |",
				"| Modified  | 2 |",
				"| Removed   | 1 |",
				"| Renamed   | 0 |",
				"**Updated capabilities**:",
				"- user-authentication",
				"- session-management",
				"- token-validation",
				"## Review Checklist",
				"- [ ] Archived change structure is complete",
				"- [ ] Spec deltas are accurate",
				"- [ ] Merged spec content is correct",
				"*Generated by `spectr pr archive`*",
			},
			absent: nil,
		},
		{
			name: "no capabilities",
			data: PRTemplateData{
				ChangeID:     "minor-update",
				ArchivePath:  "spectr/accepted/minor-update",
				Mode:         ModeArchive,
				Capabilities: nil, // empty
				Counts: archive.OperationCounts{
					Added:    1,
					Modified: 0,
					Removed:  0,
					Renamed:  0,
				},
			},
			expected: []string{
				"## Summary",
				"`minor-update`",
				"## Spec Updates",
				"| Added     | 1 |",
				"## Review Checklist",
			},
			absent: []string{
				"**Updated capabilities**:",
			},
		},
		{
			name: "nil capabilities",
			data: PRTemplateData{
				ChangeID:     "nil-caps-test",
				ArchivePath:  "spectr/accepted/nil-caps-test",
				Mode:         ModeArchive,
				Capabilities: nil, // nil
				Counts: archive.OperationCounts{
					Added:    2,
					Modified: 1,
					Removed:  0,
					Renamed:  0,
				},
			},
			expected: []string{
				"## Summary",
				"`nil-caps-test`",
			},
			absent: []string{
				"**Updated capabilities**:",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderPRBody(tt.data)
			if err != nil {
				t.Fatalf("RenderPRBody() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf("RenderPRBody() missing expected string %q\nGot:\n%s", exp, result)
				}
			}

			for _, abs := range tt.absent {
				if strings.Contains(result, abs) {
					t.Errorf("RenderPRBody() should NOT contain %q\nGot:\n%s", abs, result)
				}
			}
		})
	}
}

// TestRenderPRBody_New tests new mode PR body rendering.
func TestRenderPRBody_New(t *testing.T) {
	tests := []struct {
		name     string
		data     PRTemplateData
		expected []string
	}{
		{
			name: "basic new proposal",
			data: PRTemplateData{
				ChangeID: "add-feature-y",
				Mode:     ModeNew,
			},
			expected: []string{
				"## Summary",
				"`add-feature-y`",
				"**Location**: `spectr/changes/add-feature-y/`",
				"## Files",
				"`proposal.md` - Change overview",
				"`tasks.md` - Implementation checklist",
				"`specs/` - Delta specifications",
				"## Review Checklist",
				"- [ ] Proposal addresses the stated problem",
				"- [ ] Delta specs are properly formatted",
				"- [ ] Tasks are clear and actionable",
				"*Generated by `spectr pr new`*",
			},
		},
		{
			name: "different change id",
			data: PRTemplateData{
				ChangeID: "refactor-core",
				Mode:     ModeNew,
			},
			expected: []string{
				"`refactor-core`",
				"spectr/changes/refactor-core/",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderPRBody(tt.data)
			if err != nil {
				t.Fatalf("RenderPRBody() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf("RenderPRBody() missing expected string %q\nGot:\n%s", exp, result)
				}
			}
		})
	}
}

// TestRenderPRBody_Delete tests delete mode PR body rendering.
func TestRenderPRBody_Delete(t *testing.T) {
	tests := []struct {
		name     string
		data     PRTemplateData
		expected []string
	}{
		{
			name: "basic delete",
			data: PRTemplateData{
				ChangeID: "cli-interface",
				Mode:     ModeDelete,
			},
			expected: []string{
				"## Summary",
				"Deletes spec: `cli-interface`",
				"**Removed**: `spectr/specs/cli-interface/`",
				"## Review Checklist",
				"- [ ] Spec is no longer needed",
				"- [ ] No active changes reference this spec",
				"*Generated by `spectr pr delete`*",
			},
		},
		{
			name: "different spec id",
			data: PRTemplateData{
				ChangeID: "user-auth",
				Mode:     ModeDelete,
			},
			expected: []string{
				"`user-auth`",
				"spectr/specs/user-auth/",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := RenderPRBody(tt.data)
			if err != nil {
				t.Fatalf("RenderPRBody() error = %v", err)
			}

			for _, exp := range tt.expected {
				if !strings.Contains(result, exp) {
					t.Errorf("RenderPRBody() missing expected string %q\nGot:\n%s", exp, result)
				}
			}
		})
	}
}

// TestRenderPRBody_InvalidMode tests that invalid modes return an error.
func TestRenderPRBody_InvalidMode(t *testing.T) {
	tests := []struct {
		name string
		mode string
	}{
		{name: "empty mode", mode: ""},
		{name: "unknown mode", mode: "invalid"},
		{name: "typo", mode: "nwe"},
		{name: "case sensitive", mode: "New"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data := PRTemplateData{
				ChangeID: "test-change",
				Mode:     tt.mode,
			}
			result, err := RenderPRBody(data)
			if err == nil {
				t.Errorf(
					"RenderPRBody() expected error for mode %q, got result: %s",
					tt.mode,
					result,
				)
			}
			if !strings.Contains(err.Error(), "unknown mode") {
				t.Errorf("RenderPRBody() error should mention 'unknown mode', got: %v", err)
			}
		})
	}
}

// TestGetPRTitle tests PR title generation for different modes.
func TestGetPRTitle(t *testing.T) {
	tests := []struct {
		name     string
		changeID string
		mode     string
		expected string
	}{
		{
			name:     "archive mode",
			changeID: "add-feature",
			mode:     ModeArchive,
			expected: "spectr(archive): add-feature",
		},
		{
			name:     "new mode",
			changeID: "new-proposal",
			mode:     ModeNew,
			expected: "spectr(proposal): new-proposal",
		},
		{
			name:     "unknown mode returns default",
			changeID: "some-change",
			mode:     "unknown",
			expected: "spectr: some-change",
		},
		{
			name:     "empty mode returns default",
			changeID: "another-change",
			mode:     "",
			expected: "spectr: another-change",
		},
		{
			name:     "hyphenated change id - archive",
			changeID: "my-complex-change-id",
			mode:     ModeArchive,
			expected: "spectr(archive): my-complex-change-id",
		},
		{
			name:     "hyphenated change id - new",
			changeID: "my-complex-change-id",
			mode:     ModeNew,
			expected: "spectr(proposal): my-complex-change-id",
		},
		{
			name:     "delete mode",
			changeID: "cli-interface",
			mode:     ModeDelete,
			expected: "spectr: Delete cli-interface spec",
		},
		{
			name:     "hyphenated spec id - delete",
			changeID: "user-auth-module",
			mode:     ModeDelete,
			expected: "spectr: Delete user-auth-module spec",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GetPRTitle(tt.changeID, tt.mode)
			if result != tt.expected {
				t.Errorf(
					"GetPRTitle(%q, %q) = %q, want %q",
					tt.changeID,
					tt.mode,
					result,
					tt.expected,
				)
			}
		})
	}
}

// TestModeConstants verifies the mode constant values.
func TestModeConstants(t *testing.T) {
	if ModeArchive != "archive" {
		t.Errorf("ModeArchive = %q, want %q", ModeArchive, "archive")
	}
	if ModeNew != "new" {
		t.Errorf("ModeNew = %q, want %q", ModeNew, "new")
	}
	if ModeDelete != "delete" {
		t.Errorf("ModeDelete = %q, want %q", ModeDelete, "delete")
	}
}
